title: Pneumatics Design Wiki
description: A wiki for designing and building pneumatics projects.
theme: just-the-docs

url: https://kvriet.github.io/pneumatics

# aux_links:
  # Template Repository: https://github.com/just-the-docs/just-the-docs-template
